apiVersion: v1
kind: Template
metadata:
  name: package-releases-buildconfig
  annotations:
    description: This is Thoth Core - Package Releases Job BuildConfig
    openshift.io/display-name: "Thoth: Package Releases Job BuildConfig"
    version: 0.2.0
    tags: poc,thoth,ai-stacks,package-releases
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Package
      Releases Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: package-releases-buildconfig
    app: thoth
    component: package-releases

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: package-releases-job
      labels:
        app: thoth
        component: package-releases
    spec:
      resources:
        limits:
          cpu: 2000m
          memory: 768Mi
        requests:
          cpu: 2000m
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "package-releases-job:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret

parameters:
  - description: Name of the github repository for Thoth's Package Releases Job
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/package-releases-job'

  - description: Git reference to be used for Thoth's Package Releases Job
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
